### ISSUE TITLE
矩阵类

### ISSUE THREAD

**Issue by MrY-Cat** [MrY-Cat/my.math#4]

**Comment by MrY-Cat** [comment]
det()还有问题：
----测试[Matrix.det]开始----

1 1 1 
1 1 1 
0 1 1 

Exception in thread "main" java.lang.ArithmeticException: / by zero
	at java.base/java.math.BigDecimal.divideAndRound(BigDecimal.java:4642)
	at java.base/java.math.BigDecimal.divide(BigDecimal.java:5715)
	at java.base/java.math.BigDecimal.divide(BigDecimal.java:1636)
	at java.base/java.math.BigDecimal.divide(BigDecimal.java:1717)
	at yyd.mrycat.math.data.Matrix.det(Matrix.kt:141)
	at TestsKt.test5(Tests.kt:23)
	at TestsKt.test5$default(Tests.kt:18)
	at TestsKt.nowTest(Tests.kt:15)
	at Main$Companion.main(main.kt:8)
	at Main.main(main.kt)

**Comment by MrY-Cat** [comment]
22000*22000个int几乎消耗了超过1.8G内存，达到了电脑物理内存的1/4，JVM最大堆默认为1/4，所以这不是代码的问题，是物理内存的限制

**Comment by MrY-Cat** [comment]
矩阵的set是否有并发问题
